# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Postcuring.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pymongo import MongoClient


class Ui_PostCuring(object):
    def setupUi(self, PostCuring):
        PostCuring.setObjectName("PostCuring")
        PostCuring.resize(1024, 600)
        PostCuring.setMinimumSize(QtCore.QSize(1024, 600))
        PostCuring.setMaximumSize(QtCore.QSize(1024, 600))
        PostCuring.setStyleSheet("background-color: rgb(60, 181, 228);")
        self.centralwidget = QtWidgets.QWidget(PostCuring)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 1021, 81))
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 90, 321, 211))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(130, 20, 141, 22))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(130, 59, 113, 21))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 90, 113, 21))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(100, 140, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.uploved)
        PostCuring.setCentralWidget(self.centralwidget)

        self.retranslateUi(PostCuring)
        QtCore.QMetaObject.connectSlotsByName(PostCuring)

    def retranslateUi(self, PostCuring):
        _translate = QtCore.QCoreApplication.translate
        PostCuring.setWindowTitle(_translate("PostCuring", "MainWindow"))
        self.label.setText(_translate("PostCuring", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Post Curing</span></p></body></html>"))
        self.groupBox.setTitle(_translate("PostCuring", "Postcuring details"))
        self.label_2.setText(_translate("PostCuring", "Postcuring Unit:"))
        self.comboBox.setItemText(0, _translate("PostCuring", "--Select--"))
        self.comboBox.setItemText(1, _translate("PostCuring", "NextDent"))
        self.comboBox.setItemText(2, _translate("PostCuring", "CureM"))
        self.comboBox.setItemText(3, _translate("PostCuring", "Raplas"))
        self.label_3.setText(_translate("PostCuring", "Timer:"))
        self.label_4.setText(_translate("PostCuring", "Wavelength:"))
        self.pushButton.setText(_translate("PostCuring", "Submit"))

    def uploved(self):

        Second.printprofile['PostCuring_Type'] = self.comboBox.currentText()
        Second.printprofile['PostCuring_Timer'] = self.lineEdit.text()
        Second.printprofile['PostCuring_wavelength'] = self.lineEdit_2.text()
        print(Second.printprofile['ExposureTime'])
        client = MongoClient("mongodb+srv://user:0104@cluster0.fwiab.mongodb.net/Test?retryWrites=true&w=majority")
        db = client.get_databe('Test')
        records = db.print_data
      
import Second  
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PostCuring = QtWidgets.QMainWindow()
    ui = Ui_PostCuring()
    ui.setupUi(PostCuring)
    PostCuring.show()
    sys.exit(app.exec_())
    