# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Projection.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#import RPi.GPIO as GPIO
#import smbus
from time import sleep
import os
#######
#GPIO.setmode(GPIO.BCM)

#GPIO.setwarnings(False)

######################I2C and Engine setup#########
I2C_ADDR = 0x1b

LED_Enable = 0x52
LED_CURRENT = 0x54
DMD_FAN = 0xeb
LED_FAN1 = 0xec
LED_FAN2 = 0xed
INPUT_SOURCE = 0x01
TEST_PATTERN = 0x11
SOLID_FIELD_GENERATOR = 0x13

#i2c = smbus.SMBus(1)

#GPIO.setup(20, GPIO.OUT)
#GPIO.setup(19, GPIO.OUT)

class Ui_ProjectionWindow(object):
    def setupUi(self, ProjectionWindow):
        self.ProjectionWindow = ProjectionWindow
        ProjectionWindow.setObjectName("ProjectionWindow")
        ProjectionWindow.resize(1024, 600)
        ProjectionWindow.setMinimumSize(QtCore.QSize(1024, 600))
        ProjectionWindow.setMaximumSize(QtCore.QSize(1024, 600))
        ProjectionWindow.setStyleSheet("background-color: rgb(60, 181, 228);")
        self.centralwidget = QtWidgets.QWidget(ProjectionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 1021, 81))
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(130, 140, 231, 171))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.Projectoron = QtWidgets.QRadioButton(self.groupBox)
        self.Projectoron.setGeometry(QtCore.QRect(50, 40, 82, 31))
        #self.Projectoron.toggled.connect(self.on)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Projectoron.setFont(font)
        self.Projectoron.setObjectName("Projectoron")
        self.Projectoroff = QtWidgets.QRadioButton(self.groupBox)
        self.Projectoroff.setGeometry(QtCore.QRect(50, 86, 101, 31))
        #self.Projectoroff.toggled.connect(self.off)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Projectoroff.setFont(font)
        self.Projectoroff.setObjectName("Projectoroff")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(430, 140, 231, 171))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.LEDon = QtWidgets.QRadioButton(self.groupBox_2)
        self.LEDon.setGeometry(QtCore.QRect(50, 40, 82, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LEDon.setFont(font)
        self.LEDon.setObjectName("LEDon")
        #self.LEDon.toggled.connect(self.ledon)
        self.LEDoff = QtWidgets.QRadioButton(self.groupBox_2)
        self.LEDoff.setGeometry(QtCore.QRect(50, 80, 82, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LEDoff.setFont(font)
        self.LEDoff.setObjectName("LEDoff")
        #self.LEDoff.toggled.connect(self.ledoff)
        self.LEDPower = QtWidgets.QComboBox(self.centralwidget)
        self.LEDPower.setGeometry(QtCore.QRect(710, 240, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LEDPower.setFont(font)
        self.LEDPower.setStyleSheet("")
        self.LEDPower.setObjectName("LEDPower")
        self.LEDPower.addItem("")
        self.LEDPower.addItem("")
        self.LEDPower.addItem("")
        self.LEDPower.addItem("")
        self.LEDPower.addItem("")
        self.LEDPower.addItem("")
        self.LEDPower.addItem("")
        self.LEDPower.addItem("")
        self.LEDPower.addItem("")
        self.LEDPower.addItem("")
        self.LEDPower.addItem("")
        self.LEDPower.addItem("")
        self.LEDPower.addItem("")
        self.LEDPower.addItem("")
        self.LEDPower.addItem("")
        self.LEDPower.addItem("")
        self.LEDPower.addItem("")
        self.LEDPower.addItem("")
        self.LEDPower.addItem("")
        self.LEDPower.addItem("")
        self.LEDPower.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(710, 210, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Blackimage = QtWidgets.QPushButton(self.centralwidget)
        self.Blackimage.setGeometry(QtCore.QRect(130, 420, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Blackimage.setFont(font)
        self.Blackimage.setObjectName("Blackimage")
        self.WhiteImage = QtWidgets.QPushButton(self.centralwidget)
        self.WhiteImage.setGeometry(QtCore.QRect(290, 420, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.WhiteImage.setFont(font)
        self.WhiteImage.setObjectName("WhiteImage")
        self.Checker = QtWidgets.QPushButton(self.centralwidget)
        self.Checker.setGeometry(QtCore.QRect(450, 420, 121, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.Checker.setFont(font)
        self.Checker.setObjectName("Checker")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 370, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Setpower = QtWidgets.QPushButton(self.centralwidget)
        self.Setpower.setGeometry(QtCore.QRect(850, 240, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.Setpower.setFont(font)
        self.Setpower.setObjectName("Setpower")
        self.Setpower.clicked.connect(self.readpower)
        self.ledontime = QtWidgets.QComboBox(self.centralwidget)
        self.ledontime.setGeometry(QtCore.QRect(710, 360, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ledontime.setFont(font)
        self.ledontime.setStyleSheet("")
        self.ledontime.setObjectName("ledontime")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.ledontime.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(710, 330, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.SetTime = QtWidgets.QPushButton(self.centralwidget)
        self.SetTime.setGeometry(QtCore.QRect(850, 360, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.SetTime.setFont(font)
        self.SetTime.setObjectName("SetTime")
        self.SetTime.clicked.connect(self.setsleep)
        ProjectionWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ProjectionWindow)
        QtCore.QMetaObject.connectSlotsByName(ProjectionWindow)

    def retranslateUi(self, ProjectionWindow):
        _translate = QtCore.QCoreApplication.translate
        ProjectionWindow.setWindowTitle(_translate("ProjectionWindow", "MainWindow"))
        self.label.setText(_translate("ProjectionWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Projection</span></p></body></html>"))
        self.groupBox.setTitle(_translate("ProjectionWindow", "Projector"))
        self.Projectoron.setText(_translate("ProjectionWindow", "ON"))
        self.Projectoroff.setText(_translate("ProjectionWindow", "OFF"))
        self.groupBox_2.setTitle(_translate("ProjectionWindow", "LED"))
        self.LEDon.setText(_translate("ProjectionWindow", "ON"))
        self.LEDoff.setText(_translate("ProjectionWindow", "OFF"))
        self.LEDPower.setItemText(0, _translate("ProjectionWindow", "--Select--(%)"))
        self.LEDPower.setItemText(1, _translate("ProjectionWindow", "35"))
        self.LEDPower.setItemText(2, _translate("ProjectionWindow", "40"))
        self.LEDPower.setItemText(3, _translate("ProjectionWindow", "45"))
        self.LEDPower.setItemText(4, _translate("ProjectionWindow", "50"))
        self.LEDPower.setItemText(5, _translate("ProjectionWindow", "55"))
        self.LEDPower.setItemText(6, _translate("ProjectionWindow", "60"))
        self.LEDPower.setItemText(7, _translate("ProjectionWindow", "65"))
        self.LEDPower.setItemText(8, _translate("ProjectionWindow", "70"))
        self.LEDPower.setItemText(9, _translate("ProjectionWindow", "75"))
        self.LEDPower.setItemText(10, _translate("ProjectionWindow", "80"))
        self.LEDPower.setItemText(11, _translate("ProjectionWindow", "85"))
        self.LEDPower.setItemText(12, _translate("ProjectionWindow", "90"))
        self.LEDPower.setItemText(13, _translate("ProjectionWindow", "95"))
        self.LEDPower.setItemText(14, _translate("ProjectionWindow", "100"))
        self.LEDPower.setItemText(15, _translate("ProjectionWindow", "105"))
        self.LEDPower.setItemText(16, _translate("ProjectionWindow", "110"))
        self.LEDPower.setItemText(17, _translate("ProjectionWindow", "115"))
        self.LEDPower.setItemText(18, _translate("ProjectionWindow", "120"))
        self.LEDPower.setItemText(19, _translate("ProjectionWindow", "125"))
        self.LEDPower.setItemText(20, _translate("ProjectionWindow", "130"))
        self.label_2.setText(_translate("ProjectionWindow", "LED Power"))
        self.Blackimage.setText(_translate("ProjectionWindow", "Black Image"))
        self.WhiteImage.setText(_translate("ProjectionWindow", "White Image"))
        self.Checker.setText(_translate("ProjectionWindow", "Checker"))
        self.label_3.setText(_translate("ProjectionWindow", "Projection"))
        self.Setpower.setText(_translate("ProjectionWindow", "Set"))
        self.ledontime.setItemText(0, _translate("ProjectionWindow", "--Select--(Sec.)"))
        self.ledontime.setItemText(1, _translate("ProjectionWindow", "0.5"))
        self.ledontime.setItemText(2, _translate("ProjectionWindow", "1"))
        self.ledontime.setItemText(3, _translate("ProjectionWindow", "1.5"))
        self.ledontime.setItemText(4, _translate("ProjectionWindow", "2"))
        self.ledontime.setItemText(5, _translate("ProjectionWindow", "2.5"))
        self.ledontime.setItemText(6, _translate("ProjectionWindow", "3"))
        self.ledontime.setItemText(7, _translate("ProjectionWindow", "3.5"))
        self.ledontime.setItemText(8, _translate("ProjectionWindow", "4"))
        self.ledontime.setItemText(9, _translate("ProjectionWindow", "4.5"))
        self.ledontime.setItemText(10, _translate("ProjectionWindow", "5"))
        self.ledontime.setItemText(11, _translate("ProjectionWindow", "5.5"))
        self.ledontime.setItemText(12, _translate("ProjectionWindow", "6"))
        self.ledontime.setItemText(13, _translate("ProjectionWindow", "6.5"))
        self.ledontime.setItemText(14, _translate("ProjectionWindow", "7"))
        self.ledontime.setItemText(15, _translate("ProjectionWindow", "7.5"))
        self.ledontime.setItemText(16, _translate("ProjectionWindow", "8"))
        self.ledontime.setItemText(17, _translate("ProjectionWindow", "8.5"))
        self.ledontime.setItemText(18, _translate("ProjectionWindow", "9"))
        self.ledontime.setItemText(19, _translate("ProjectionWindow", "9.5"))
        self.ledontime.setItemText(20, _translate("ProjectionWindow", "10"))
        self.ledontime.setItemText(21, _translate("ProjectionWindow", "10.5"))
        self.ledontime.setItemText(22, _translate("ProjectionWindow", "11"))
        self.ledontime.setItemText(23, _translate("ProjectionWindow", "12"))
        self.ledontime.setItemText(24, _translate("ProjectionWindow", "13"))
        self.ledontime.setItemText(25, _translate("ProjectionWindow", "14"))
        self.ledontime.setItemText(26, _translate("ProjectionWindow", "15"))
        self.ledontime.setItemText(27, _translate("ProjectionWindow", "16"))
        self.ledontime.setItemText(28, _translate("ProjectionWindow", "17"))
        self.ledontime.setItemText(29, _translate("ProjectionWindow", "18"))
        self.ledontime.setItemText(30, _translate("ProjectionWindow", "19"))
        self.ledontime.setItemText(31, _translate("ProjectionWindow", "20"))
        self.ledontime.setItemText(32, _translate("ProjectionWindow", "25"))
        self.ledontime.setItemText(33, _translate("ProjectionWindow", "30"))
        self.ledontime.setItemText(34, _translate("ProjectionWindow", "35"))
        self.ledontime.setItemText(35, _translate("ProjectionWindow", "40"))
        self.ledontime.setItemText(36, _translate("ProjectionWindow", "45"))
        self.ledontime.setItemText(37, _translate("ProjectionWindow", "50"))
        self.ledontime.setItemText(38, _translate("ProjectionWindow", "55"))
        self.ledontime.setItemText(39, _translate("ProjectionWindow", "60"))
        self.label_4.setText(_translate("ProjectionWindow", "LED on in seconds"))
        self.SetTime.setText(_translate("ProjectionWindow", "Sleep"))


    def on_close(self): #to close the Second window by clicking back button
        # win2 = QMainWindow()
        # ui = Ui_Win2()
        # ui.setupUi(win2)
        self.SecondWindow.close()

#-----------------------------------------------------------------------
        #To turn the Projector on
#-----------------------------------------------------------------------
    def on(self):
        GPIO.output(20, GPIO.HIGH)
        print("check light")
#-----------------------------------------------------------------------
        #To turn off the projector
#-----------------------------------------------------------------------
    def off(self):
        GPIO.output(20,GPIO.LOW)
        print("Projector off")
#-----------------------------------------------------------------------
        #To turn the projector LED on
#-----------------------------------------------------------------------
    def ledon(self):
        #self.SetGPIO()
        #i2c.write_i2c_block_data(I2C_ADDR, 0x52, 0x02)
        i2c.write_byte_data(I2C_ADDR, 0x52,0x07)
        GPIO.output(6, GPIO.HIGH) #HIgh to turn ON UV LED
        time.sleep(timesleep)
        #os.system("sudo blackimage")
        print("P LED On")
        sleep(1)
#-----------------------------------------------------------------------
        #To turn the projector LED off
#-----------------------------------------------------------------------
    def ledoff(self):
        #self.SetGPIO()
        i2c.write_byte_data(I2C_ADDR, 0x52,0x00)
        #i2c.write_i2c_block_data(I2C_ADDR, LED_CURRENT, 0x00)
        GPIO.output(19, GPIO.LOW) #LOw to turn off the UV LED
        print("P LED Off")

    def TestPattern(sel):
        if(sel==0): #test pattern off
            i2c.write_byte_data(I2C_ADDR,INPUT_SOURCE,0)    #select external source from hdmi
        elif(sel==1): #test pattern  checkerboard
            i2c.write_byte_data(I2C_ADDR,INPUT_SOURCE,1)    #select input test pattern source
            val = [0x87,0x70,0x04,0x00,0x02,0x00];          #select checkerboard test pattern
            i2c.write_i2c_block_data(I2C_ADDR,TEST_PATTERN,val)
        return

    def SetLedCurrent(self):
        i2c.write_i2c_block_data(I2C_ADDR,LED_CURRENT_WR,val)
        return

    def readpower(self):
        readee = int(self.LEDPower.currentText())
        print(readee)
        power = int(readee * 1.5)
        global val
        val = [power, 0, power, 0, power , 0]
        print(val)
        self.SetLedCurrent()

    def setsleep(self):
        global timesleep
        timesleep = float(self.ledontime.currentText())
        print(timesleep)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProjectionWindow = QtWidgets.QMainWindow()
    ui = Ui_ProjectionWindow()
    ui.setupUi(ProjectionWindow)
    ProjectionWindow.show()
    sys.exit(app.exec_())
